name: Günlük Hal Verisi Çekme

on:
  schedule:
    - cron: '30 4 * * *'  # UTC 04:30 = Türkiye saatiyle 07:30
  workflow_dispatch:      # Elle tetikleme desteği

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Repo'yu klonla
        uses: actions/checkout@v3

      - name: Python kurulumunu yap
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Gerekli paketleri kur
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Scraper'ı çalıştır
        run: python backend/scraper.py

      - name: Değişiklikleri GitHub'a gönder
        env:
          miote: ${{ secrets.miote }}
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${miote}@github.com/${{ github.repository }}
          git add hal_fiyatlari.db
          git commit -m "Veritabanı güncellendi: $(date '+%Y-%m-%d')" || echo "Değişiklik yok"
          git push
