name: Hal Fiyatlarını Güncelle

on:
  schedule:
    - cron: '30 4 * * *'  # Her gün saat 07:30'da Türkiye saatiyle
  workflow_dispatch:

jobs:
  scrape-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Reposuyu klonla
        uses: actions/checkout@v3

      - name: Python kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Gerekli paketleri kur
        run: |
          pip install requests beautifulsoup4

      - name: Script'i çalıştır
        run: |
          python backend/scraper.py

      - name: Değişiklikleri GitHub'a gönder
        env:
          GH_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          git add hal_fiyatlari.db
          git commit -m "Veritabanı güncellendi: $(date '+%Y-%m-%d')" || echo "Değişiklik yok"
          git push
