name: Veritabanı Güncelle

on:
  schedule:
    - cron: "30 4 * * *"  # Her gün saat 07:30'da (UTC+3 için 04:30 UTC)
  workflow_dispatch:      # Manuel çalıştırma için

permissions:
  contents: write         # GITHUB_TOKEN ile push izni verir

jobs:
  update-db:
    runs-on: ubuntu-latest

    steps:
      - name: Repo'yu klonla
        uses: actions/checkout@v3

      - name: Python kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Gerekli paketleri yükle
        run: pip install -r requirements.txt

      - name: Veritabanını güncelle
        run: python backend/scraper.py

      - name: Git ayarları ve push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add hal_fiyatlari.db
          git commit -m "Veritabanı güncellendi: $(date '+%Y-%m-%d')" || echo "Değişiklik yok"
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }} HEAD:main
